org: "armbian" # can't be an expression, only string.
org_and_build_repo: "armbian/build"
build_ref: "main"
ghcr_user: "${{ github.repository_owner }}"
userpatches_config_for_prepare_job: "" # use "" for no config file
