name: "Build Daily Releases (youyeetoo-r1-v3)"
on:
  schedule:
    - cron: "0 0 * * *"  
  workflow_dispatch:

jobs:
  build:
    name: "Build Armbian"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        armbian_release: [noble, bookworm, trixie]
        armbian_ui: [gnome, server]
        armbian_kernel_branch: [vendor, edge, current]
        exclude:
          - armbian_release: trixie
            armbian_ui: gnome
          - armbian_ui: gnome
            armbian_release: trixie
    steps:
      - name: "Build Armbian"
        uses: armbian/build@v24.2.1
        with:
          armbian_target:             "build"
          armbian_release:            "${{ matrix.armbian_release }}"
          armbian_kernel_branch:      "${{ matrix.armbian_kernel_branch }}"
          armbian_ui:                 "${{ matrix.armbian_ui }}"
          armbian_board:              "youyeetoo-r1-v3"
        continue-on-error: true 

      - name: "Upload build artifacts"
        uses: actions/upload-artifact@v3
        with:
          path: build/output/images/*
        continue-on-error: true

  create_release:
    name: "Create GitHub Release"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: "Download all artifacts"
        uses: actions/download-artifact@v3
        with:
          path: ./artifacts/

      - name: "Create GitHub release and upload assets"
        uses: ncipollo/release-action@v1
        with:
          tag: "armbian-unofficial-release-$(date +%Y-%m-%d)"
          name: "Release Armbian Unofficial - $(date +%Y-%m-%d)"
          artifacts: "./artifacts/*"
          body: |
            Build details:
            - Board: Youyeetoo R1 v3
            - Release: noble, bookworm, trixie
            - UI: gnome, server
            - Kernel: vendor, edge, current
            This release contains all versions built for the `youyeetoo-r1-v3` board.
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          removeArtifacts: false
          replacesArtifacts: true
          makeLatest: true
