name: "Build Daily Releases (youyeetoo-r1-v3)"
on:
  schedule:
    - cron: "0 0 * * *" 

jobs:
  build:
    name: "Build Armbian"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        armbian_release: [noble, bookworm, trixie]
        armbian_ui: [gnome, server]
        armbian_kernel_branch: [vendor, edge, current]
        exclude:
          - armbian_release: trixie
            armbian_ui: gnome
          - armbian_ui: gnome
            armbian_release: trixie
    steps:
      - name: "Check if build is valid"
        run: |
          if [[ "${{ matrix.armbian_ui }}" == "gnome" && "${{ matrix.armbian_release }}" == "trixie" ]]; then
            echo "Skipping GNOME build for Trixie"
            exit 0
      - uses: armbian/build@v24.2.1
        with:
          armbian_token:              "${{ secrets.GITHUB_TOKEN }}"
          armbian_target:             "build"
          armbian_release:            "${{ matrix.armbian_release }}"
          armbian_kernel_branch:      "${{ matrix.armbian_kernel_branch }}"
          armbian_ui:                 "${{ matrix.armbian_ui }}"
          armbian_board:              "youyeetoo-r1-v3"
          armbian_release_title:      "Release Armbian Unofficial"
          armbian_release_body:       |
            Build details:
            - Board: youyeetoo-r1-v3
            - Kernel: ${{ matrix.armbian_kernel_branch }}
            - Release: ${{ matrix.armbian_release }}
            - UI: ${{ matrix.armbian_ui }}
          armbian_pgp_key:            "${{ secrets.GPG_KEY1 }}"
          armbian_pgp_password:       "${{ secrets.GPG_PASSPHRASE1 }}"
