#
# This action recreate action for building stable images
#
name: Recreate Matrix
on:
  push:
    branches:
      - 'main'
    paths:
      - "userpatches/*"
      - "userpatches/gha/**"
      - "userpatches/gha/chunks/**"

  workflow_dispatch:
  repository_dispatch:
    types: [Recreate Matrix]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:

  build:
    name: Recreate action
    if: ${{ github.repository_owner == 'Armbian' }}
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Armbian Framework
      uses: actions/checkout@v3.5.2
      with:
        persist-credentials: false
        repository: armbian/build
        ref:  main
        fetch-depth: 1
        clean: false
        path: build

    - name: Checkout Armbian OS Config
      uses: actions/checkout@v3.5.2
      with:
        persist-credentials: false
        repository: armbian/os
        ref:  main
        clean: false
        fetch-depth: 0
        path: os

    - name: "Rsync userpatches"
      run: |

        rsync -av os/userpatches/. build/userpatches/

    - name: "Generate Action Script"
      run: |

        cd build

        # generate for trunk
        sed -i 's/build_ref: .*/build_ref: "main"/' userpatches/gha/gha_config.yaml
        sed -i 's/script_name: .*/script_name: "Artifacts main"/' userpatches/gha/gha_config.yaml
        bash ./compile.sh gha-template
        cp output/info/artifact-image-complete-matrix.yml ../os/.github/workflows/complete-artifact-matrix-beta.yml

        # generate for latest stable branch
        sed -i 's/build_ref: .*/build_ref: "v23.05"/' userpatches/gha/gha_config.yaml
        sed -i 's/script_name: .*/script_name: "Artifacts v23.05"/' userpatches/gha/gha_config.yaml
        bash ./compile.sh gha-template
        cp output/info/artifact-image-complete-matrix.yml ../os/.github/workflows/complete-artifact-matrix-stable.yml

        cd ../os
        git config --local user.email "info@armbian.com"
        git config --local user.name "Armbianworker"
        #git pull --rebase
        git add .github/workflows/complete-artifact-matrix-beta.yml
        git add .github/workflows/complete-artifact-matrix-stable.yml
        git commit --allow-empty -m "Update generated GHA chunk workflow artifact-image-complete-matrix.yml" -a

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        repository: armbian/os
        branch: ${{ github.ref }}
        directory: os
