name: Repository update (admin)
on:
#  repository_dispatch:
#    types: ["Repository update"]
#  schedule:
#    - cron: "00 3 * * *"
  workflow_dispatch:
    inputs:
      BUILD_BRANCH:
        description: Build branch
        required: false
        default: main
        type: string
      BUILD_RUNNER:
        description: Build runner
        required: false
        default: ubuntu-latest
        type: string
      TARGET_REPOSITORY:
        type: choice
        description: Select repository
        options:
        - beta.armbian.com
        - apt.armbian.com
      UPDATE_REPOSITORY:
        type: boolean
        description: Update repository
        default: true

concurrency:
  group: repository-${{ github.ref }}
  cancel-in-progress: false

jobs:

  Artifacts:

    name: Upload artifacts
    runs-on: fast
    steps:

      - name: "Check membership"
        uses: armbian/actions/team-check@main
        with:
          ORG_MEMBERS: ${{ secrets.ORG_MEMBERS }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  external:
    name: "Download external"
    needs: Artifacts

    if: ${{ github.repository_owner == 'Armbian' }}
    uses: armbian/scripts/.github/workflows/download-and-test-external.yml@main
    with:
      ACCESS_NAME: armbian
      BUILD_RUNNER: ${{ inputs.BUILD_RUNNER }}
    secrets:
      GPG_KEY1: ${{ secrets.GPG_KEY1 }}
      GPG_PASSPHRASE1: ${{ secrets.GPG_PASSPHRASE1 }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      KEY_UPLOAD: ${{ secrets.KEY_UPLOAD }}
      HOST_UPLOAD: ${{ secrets.HOST_UPLOAD }}
      HOST_UPLOAD_USER: ${{ secrets.HOST_UPLOAD_USER }}
      HOST_UPLOAD_PORT: ${{ secrets.HOST_UPLOAD_PORT }}
      KNOWN_HOSTS_ARMBIAN_UPLOAD: ${{ secrets.KNOWN_HOSTS_ARMBIAN_UPLOAD }}
