name: Test
on:
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    name: "Test1234"
    runs-on: [ "ubuntu-latest" ]
    steps:

      - name: "Restart ${{ matrix.script }}.yml"
        run: |
          gh release list | awk '{print $1;}' | tail -n +4 | xargs -L1 gh release delete     
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
