name: Test
#
# Update artifacts on PR
#

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    
jobs:

  Compile:

#    if: ${{ github.repository_owner == 'Armbian' }}
    uses: armbian/os/.github/workflows/complete-artifact-matrix-all.yml@main
    secrets:
      ACCESS_TOKEN_ARMBIANWORKER: ${{ secrets.ACCESS_TOKEN_ARMBIANWORKER }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
#      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ORG_MEMBERS: ${{ secrets.ORG_MEMBERS }}
    with:
      ref: "3c137e113f6894a4abce0d41014e2d3a832058fe"
      #ref: ${{ github.event.pull_request.head.sha }}
