name: Test
on:
  workflow_dispatch:

jobs:

  build:
    name: Recreate action
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Armbian Framework
        uses: actions/checkout@v3.5.2
        with:
          persist-credentials: false
          repository: armbian/build
          ref:  AR-1582
          fetch-depth: 0
          clean: false
          path: build
    
      - run: env
      - run: |
          echo "a: $RUNNER_NAME"
      - run: |
          echo "b ${{ env.RUNNER_NAME }}"
      - name: "Compile"
        run: |
   
          # calculate loop from runner name
          if [[ -n "${ImageOS}" ]]; then
          USE_FIXED_LOOP_DEVICE=$(echo ${RUNNER_NAME} | rev | cut -d"-" -f1  | rev | sed 's/^0*//' | sed -e 's/^/\/dev\/loop/')
          fi
          ./compile.sh USE_FIXED_LOOP_DEVICE=$USE_FIXED_LOOP_DEVICE BOARD=udoo BRANCH=current RELEASE=jammy BUILD_DESKTOP=no KERNEL_CONFIGURE=no BUILD_MINIMAL=yes
