name: Test
#
# Update artifacts on PR
#

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    
jobs:

  Check:
  
    runs-on: ubuntu-latest
    outputs:
      member: ${{ steps.checkUserMember.outputs.isTeamMember }}
    steps:
    
      -  uses: tspascoal/get-user-teams-membership@v2
         id: checkUserMember
         with:
           username: ${{ github.actor }}
           organization: armbian
           team: "Board Maintainers"
           GITHUB_TOKEN: ${{ secrets.ORG_MEMBERS }}

  Compile:
    needs: Check
    name: "Runner clean ${{ needs.Check.outputs.member }}"
    if: ${{ github.repository_owner == 'Armbian' &&  needs.Check.outputs.member == 'true' }}
    uses: armbian/os/.github/workflows/complete-artifact-matrix-all.yml@main
    secrets:
      ACCESS_TOKEN_ARMBIANWORKER: ${{ secrets.ACCESS_TOKEN_ARMBIANWORKER }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
#      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ORG_MEMBERS: ${{ secrets.ORG_MEMBERS }}
    with:
      ref: "3c137e113f6894a4abce0d41014e2d3a832058fe"
      #ref: ${{ github.event.pull_request.head.sha }}
