name: Testxxx
on:
  workflow_dispatch:

jobs:

 test:

    name: "Test"
    runs-on: ubuntu-latest
    outputs:
      max-parallel: 18
      matrix:  ${{steps.json.outputs.JSON_CONTENT}}
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: armbian/os
          path: os
          fetch-depth: '2'
          clean: false

      - name: "Make JSON"
        id: json
        run: |

          dockerimages=("debian:bookworm" "ubuntu:jammy" "ubuntu:noble")
          packages=($(grep -rw os/external/*.conf -e amd64 | cut -d"/" -f3 | cut -d"." -f1))
          for i in "${packages[@]}"; do
              . os/external/${i}.conf
              if [[ -n "${INSTALL}"  && "${ARCH}" == *amd64* ]]; then
              if [[ $RELEASE != all ]]; then
              for j in ${dockerimages[@]}; do
                  elements=($(echo $RELEASE | tr ':' "\n"))
                  for SELECTED_RELEASE in "${elements[@]}"; do
                  if [[ $j == *"${SELECTED_RELEASE}"* ]]; then
                  echo "${i} -> $j -> $INSTALL"
                  fi
                  done
              done
              fi
              fi
          done

 gradle:
    needs: test
    strategy:
      fail-fast: false
      max-parallel: 32
      matrix:
        image: ${{ fromJSON(needs.test.outputs.matrix) }}

    name: "I"
    timeout-minutes: 30
    runs-on: ubuntu-latest
    container:
        image: "${{ matrix.image.image }}"
    steps:

      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: assets-for-download
          path: downloads
