name: XBuild Nightly Images
on:

  schedule:
#    - cron: "00 0 * * *"
    - cron: "0 */8 * * *"
  workflow_dispatch:

jobs:

  dispatch:
    name: "Dispatch"
    if: ${{ github.repository_owner == 'Armbian' }}
    outputs:
      version: ${{steps.releases.outputs.version}}
    needs: generaterelease
    strategy:
      matrix:
        repo: ['armbiankappa/os']
    runs-on: ubuntu-latest
    steps:

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.DISPATCH_3 }}
          repository: ${{ matrix.repo }}
          event-type: "Build"
          client-payload: '{"release": "nightly","board": "${{ github.event.inputs.board }}","config": "${{ needs.generaterelease.outputs.build_config }}", "version": "${{ needs.generaterelease.outputs.version }}"}'

      - name: Save
        id: releases
        run: |
          echo "version=${{ needs.generaterelease.outputs.version }}" >> $GITHUB_OUTPUT
